version: "3.9"
services:
  mongo_db:
    image: mongo
    volumes:
      - mongo_db:/data/db

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
        MONGO_DB_URL: mongodb://mongo_db:27017/calender
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo_db

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  mongo_db:
